services:

  postgres:
    image: postgis/postgis:17-3.5

    container_name: gis-postgres

    restart: unless-stopped

    environment:
      POSTGRES_DB: gisdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: